# Generated by Django 4.2.6 on 2023-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='word_count',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
